apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chizchig/kustomize_argocd.git
    targetRevision: HEAD
    path: infra/app/overlay/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true